export * from "@/features/authslice/authslice"
export * from "@/features/dashboardslice/dashboardslice"
export * from "@/features/patientsslice/patientslice"
export * from "@/features/doctorsslice/doctorslice"
export * from "@/features/catagreyslice/catagreyslice"
export * from "@/features/catagreyslice/catagreyslice"
